== EE4J PMC Meeting #8
== General
Date: 2018-02-27

Present:

* Dmitry
* Mark
* Steve
* Ivar
* Kevin
* Wayne

== Project Proposals

=== Status

Go through current proposals and mark those that are ok

Eclipse Project for Enterprise Security (API) - *ok*

Eclipse Soteria - *ok*

Eclipse Project for Enterprise Management - _see next agenda item_

=== How to handle platform projects

The PMC discussed how to handle inactive projects with stable code bases like “Eclipse Project for 
Enterprise Management“. The problem is to find initial committers and leads as these are practically 
dead projects.

*Short Term Solution:*
Add as a repo in Eclipse Glassfish and move it together. If it does not work out, we can figure 
it out later

*Longer Term Solution:*
We probably need a group (e.g. architecture committee) to keep the specs aligned. Specs needs to 
follow the guidelines/rules by this group. May be a task of the specification committee?
The PMC is responsible for ensuring that the projects are coherent and approve releases. Process may 
be defined such in order to approve a release, the architecture committee must have reviewed and 
checked that the guidelines are followed.

This process will most likely differ between major, minor, maintenance and patch releases. 
*Note that, the Eclipse Development Process does not require release reviews for patch (service) releases 
and so the EMO will not request approval for service releases from the PMC.*

=== New projects

* JSR 330 DI
+
The PMC needs to contact spec leads and see if they are willing to transfer to EE4J?
Or is this JSR actually considered a part of CDI?
+
Actions:
+
-> Mark talk to Weld team
+
-> Ivar mail Rob and Bob (the spec leads)

* JAX-WS
+
Actions:
+
-> David is working with Dan Kulp to see if he can take the project leader role

=== Ozark Licensing and Naming

Ozark is currently Apache 2.0 licensed. The PMC supports the decision to keep that license and 
approves this request to be sent to the Eclipse Board of Directors.

Before doing so, the PMC should add a slide stating that the PMC approves and highlight why.

Trademark Issue with Ozark. Need to find a new name. This will be handled by the proposed project 
leads in parallel with the license issue.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=528915 

== Milestones (success criterias)

The PMC discussed the criteria for a successful platform release. Is it applicable to 
GlassFish alone, or all the components + GlassFish?

*Options:*

. Each component must be released and integrated into Eclipse GlassFish. This will mean a minor 
release of all specs in order to keep the version numbers apart from the original ones.
. The APIs must be the official released as Java EE 8. The impl built from Eclipse sources. 
The APIs treated as third party content?

Actions:

-> Wayne digs in history and articulate something on the pmc list. We need to be crystal clear and 
aligned.

== Next Meeting

Tuesday March 13 at 16:00 CET
