= EE4J PMC Meeting #4

== General

Date: 2018-01-16

Present:

* Mark
* Kevin
* Dmitry
* Wayne
* Steve
* David
* Ivar

== PMC Statement about Quality Control

Discussion about how to handle updates to transfered projects until the legal agreements between Oracle and Eclipse 
have been signed. Outcome of discussion is that the PMC suggests that:

* the version to be released as the first release of “EE4J” which pass the Java EE 8 TCKs should be kept 
in a separate *protected* branch. 
* this branch has to be named ee4j_8 to communicate the compatibility with Java EE 8
* the master branch will be the next version, possibly version 9

Guidelines must be communicated to the community as soon as possible. 
Eclipse and Oracle will provide the text to communicate.

== Licensing Concerns for Implementation Projects

Discussion whether it makes sense to require the same license for implementation projects as for the API and spec projects.

There is no requirement from Eclipse Foundation that subprojects follow the parent project. The PMC may allow sub-projects 
deviate from the parent project licensing. We will look at this from case to case and if it becomes the norm, we will 
revisit this item again.
