= EE4J PMC Meeting #2019-16

== General

Date: 2019-07-09

Present:

* Kevin
* Dmitry
* David
* Ivar

== Action Items

Reviewed, discussed and updated the GitHub Issues, https://github.com/eclipse-ee4j/ee4j/issues.

== Jakarta EE 8

== Specification Projects Creation

https://github.com/orgs/eclipse-ee4j/projects/13

Round 1 - completed +
Round 2 - completed + 
Round 3 - awaiting status from Wayne

== Specification Documents

.Instructions 
https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release

- [x] Create Issue in each project with ref to the above document a checkbox list with the items - Ivar
- [x] Create a tracking board - Ivar
- [x] Email on the PMC list + jakarta community list - Ivar
- [x] Each pmc member emails the project leads in their organization
- [x] Assist the projects and follow up progress - ALL

David suggested automating the creation of boilerplate specifications. 
Volunteered to create a descriptor file for spec projects to use for scripting and a script to generate PRs in the spec repos for boilerplate specs.

.Tracking
https://github.com/orgs/eclipse-ee4j/projects/15 

The skeleton spec documents are a requirement for the Jakarta EE 8 release!
Suggestion to shorten the review period for the specs in order to be able to make it. Will bring it to the specification committee.

=== Licenses 
Should everything in a github repo have the same license? 
In the spec folder, there is a different license, pom.xml and project itself.
What is the right approach? 
Dmitry posts on the pmc list.

Question for Wayne for clarification.

.Clarification

_Generally yes. It's just generally better for consumers of content to have everything under as uniform a license as possible._ 

_But it is common for examples or configuration to be under a EDL, for example._ 

*Why are there different licenses?* _The source for the specification document should be under the project license (the distribution form of the document in the Final Specification will be under the EFSL)._

=== Versioning

Planning to release spec using the same version number. 
API jars have different versions.

Discussed wheter the PMC shouold recommend anything, e.g.:

* Spec+API have same version
* Umbrella spec ref other specs by major.minor
* patch/service releases may never change the api

== Next Meeting

Tuesday, Jul 16 at 17:00 CEST (11:00 EDT)

