= EE4J PMC Meeting #2019-07

== General

Date: 2019-04-09

Present:

* David
* Kenji
* Tanja
* Kevin
* Steve
* Wayne
* Dmitry
* Ivar

== Action Items

Reviewed, discussed and updated the GitHub Issues, https://github.com/eclipse-ee4j/ee4j/issues.

== Jakarta EE 8

=== Scope Statements

Scope statements for the API projects must be produced in order to be able to convert them into Specification Projects.

.Tracking:
https://github.com/orgs/eclipse-ee4j/projects/10 

.Actions
* [x] Create a couple of examples and refer to them on the eclipse wiki (Ivar and Wayne)
* [x] Create an issue for each project with tasks for creating scope statements (Ivar)
* [x] Set up a board to follow the status of scope statements on GitHub (Ivar)
* [ ] Reach out to projects to create their scope statements  (PMC)
* [ ] Get approval from the Spec Committee for the scope statements
* [ ] Verify that the list is complete (Ivar)

.Discussion:
What new projects do we have to create? Committers etc.
Create spec project for JSF
Discussed Create impl project for javamail? There are others as well.

Progress on names and scope statements.
Wayne will email project leads.
PMC will follow up. 
Request steering committee to explain why names must change.

=== Specification Names

Specifications (and the specification projects) must be renamed in order to be converted into Specification Projects.

.Tracking:
https://github.com/orgs/eclipse-ee4j/projects/11 

.Actions 
* [x] Set up board to follow the status of renaming (Ivar)
* [x] Create issues for each project/specification on GitHub (Ivar)
* [ ] Communicate why this is necessary
* [ ] Publish an official naming standard
* [ ] Get approval from the Spec Committee for the names


== Frequency of PMC meetings

Do we need weekly meetings? Defer the decision at least until next meeting.

== Next Meeting

Tuesday, April 23 at 17:00 CEST (11:00 EDT)

