= EE4J PMC Meeting #2019-17

== General

Date: 2019-07-16

Present:

* Kevin
* Dmitry
* David
* Mark
* Ed
* Steve
* Tanja

== Action Items (skipped)

Reviewed, discussed and updated the GitHub Issues, https://github.com/eclipse-ee4j/ee4j/issues.

== Jakarta EE 8

=== Submit Ballot PRs

David will send a note to Project Spec Leads mailing list pointing out the need for PR Ballot, Process, and Deadlines.  
Friday, July 12 is the deadline for Draft PRs for all Specifications.

Use GitHub workflow to our advantage. 
Use PR Reviews/Approvals process to tally votes.

=== TCK Education Meeting (July 15)

Q&A session on the TCK process.  
Fairly well received.  
Arjan provided most of the questions.  
Most projects reps on the call indicated that individual TCK jobs were on the horizon.

=== Projects 15 discussion

https://github.com/orgs/eclipse-ee4j/projects/15 

Dmitry will send a note to Spec Project Leads asking them to update the issues associated with this Project dashboard.  
The issues need to be assigned to an individual or have some items checked off (x of 6 work items) to be considered “In Progress”.  
Getting to 5 of 6 checkmarks is the end game for now.  
When all votes tallied, then we can do Step 6 and promote to Maven Central.

(Nothing else covered from this point on…)

== Specification Projects Creation  (Done, 07/16/2019) 

https://github.com/orgs/eclipse-ee4j/projects/13

Round 1 - completed +
Round 2 - completed + 
Round 3 - complete tomorrow + a JSF project

== Specification Documents

.Instructions 
https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release

Create Issue in each project with ref to the above document a checkbox list with the items - Ivar
Create a tracking board - Ivar
Email on the PMC list + jakarta community list - Ivar
Each PMC member emails the project leads in their organization
Assist the projects and follow up progress - ALL
Create a descriptor file for spec projects to use for scripting. E.g. in the root of each spec repo
Contain: Name, scope statement, version, etc…

Update 07/16/2019:  David provided a script for creating boilerplate Specs for all of the remaining Spec repos.  Thank you!  These initial updates were merged and then further refined by the individual Projects.



.Tracking
https://github.com/orgs/eclipse-ee4j/projects/15 

The skeleton spec documents are a requirement for the Jakarta EE 8 release!
Suggestion to shorten the review period for the specs in order to be able to make it. Spec committee?

.Licenses
Should everything in a github repo have the same license? Question for Wayne for clarification.
In the spec folder, there is a different license, pom.xml and project itself
What is the right approach? Dmitry posts on the pmc list.

.Versioning
Planning to release spec using the same version number 
API jars have different versions.
PMC recommends: 

Spec+API have same version +
Umbrella spec ref other specs by major.minor +
patch/service releases may never change the api

TCK should be discussed on the spec committee

== Next Meeting

Tuesday, Jul 23 at 17:00 CEST (11:00 EDT)
