= EE4J PMC Meeting #2019-01

== General

Date: 2019-01-15

Present:

* Tanja
* Wayne
* Dmitry
* Kevin
* David
* Ivar

*NOTE That we now have a shared calendar.*

== Action Items

Reviewed, discussed and updated the GitHub Issues, https://github.com/eclipse-ee4j/ee4j/issues.

== Eclipse GlassFish 5.1 status

Dmitry covered the status. 
We have a *green* CTS build!
Thanks to everybody that helped to get this done!

*TODOs:*

 * Release public components to Maven central
 * Release Glassfish components that depend on the above
 * Re-run the CTS on the new build
 * 4 CQs pending

A bug has been created for switching from OSSRH to Nexus Pro to support GF builds better in the future.

Discussed that there should be a build of the TCK made available as soon as possible. 
An open source build (not officially licensed). 

*Action: David creates a github issue to track this.*

== EE4J Representative on the Security Team

Email: security@eclipse.org

The security team should have a rep from the EE4J PMC to ensure that messages related to EE4J projects are handled.
There is a private bugzilla component where vulnerability reports are stored. 
The team create/identify issues in this bugzilla component and includes the project lead.

More information at https://eclipse.org/security 

*ACTION: Select a rep on the next meeting.*

== Split EE4J?

Followed up on the discussion regarding splitting up EE4J (and with that the PMC as well).
The split would in practice be to split out the implementation projects to a GlassFish top level project with its own PMC and rename the EE4J project to Jakarta (or Jakarta EE?).
Minor updates would be needed to the EE4J charter and a new charter for the GlassFish project would need to be written.

The PMC discussed that we possibly could split EE4J into GlassFish and Jakarta sometime after the 5.1 release.

The reason for this is that we don’t know the timeline for GlassFish 5.2 and don’t want this split to cause any further delays.

== Jakarta EE Roadmap

The PMC encourages the Jakarta EE Platform Specification project to start the work with creating a roadmap for Jakarta EE. 

== Jakarta EE 8 Release

*Assumption: Jakarta EE 8 == Java EE 8 ie. no additional specifications, API, behavioral changes or new profiles.*

*Jakarta EE 8 release*

Will consist of the following:

 * Specification (documents and APIs) for the full platform including full and web profiles
 * TCKs (source and binaries); part of the TCKs are documents on how to use TCKs
the Jakarta EE 8 will not attempt refactoring of the current monolith of the Java EE 8 TCK
 * Specifications that already have a separate TCK will remain as is
 * A Compatible Implementation of the full and web profiles, at least one,  available under open source license;

Required for the release:

 * Jakarta EE Specification Process  needs to be completed
 * Jakarta EE TCK process needs to be defined
 * Means to publish Final Specifications and related TCKs
 * Branding process and logo usage guidelines

== Jakarta EE Town Hall Meeting

*January 30th 11AM EST.*

Open for everyone!
The PMC will participate in the panel.

== How to engage contributors

This is a topic for the Town Hall.
Tanja will create a strawman for the message.

== Next Meeting

Tuesday, Jan 29 at 17:00 CET

